if BUILDSYSTEM_OPENWRT
SUBDIRS = qcom/mbb/default/ConfigSessionUtils qcom/mbb/default/ConfigSessionAlsaPcm qcom/mbb/default/ConfigSessionAlsaVoice qcom/mbb/default/ConfigSessionAlsaCompress
else
SUBDIRS = qcom/telematics/default/ConfigSessionUtils qcom/telematics/default/ConfigSessionAlsaPcm qcom/telematics/default/ConfigSessionAlsaVoice qcom/telematics/default/ConfigSessionAlsaCompress
endif
