usr/lib/*/*.so
usr/lib/*/*.so.*
etc/mixer_paths_qcm6490_idp.xml /etc/
etc/mixer_paths_qcm6490_rb3.xml /etc/
etc/mixer_paths_qcm6490_rb3_ia.xml /etc/
etc/mixer_paths_qcm6490_rb3_vc.xml /etc/
etc/mixer_paths_qcm6490_rb3_vision.xml /etc/
etc/mixer_paths_qcs8300_ridesx.xml /etc/
etc/mixer_paths_qcs9075_rb8.xml /etc/
etc/mixer_paths_qcs9100_ridesx.xml /etc/
etc/resourcemanager_qcm6490_idp.xml /etc/
etc/resourcemanager_qcm6490_rb3.xml /etc/
etc/resourcemanager_qcm6490_rb3_ia.xml /etc/
etc/resourcemanager_qcm6490_rb3_vc.xml /etc/
etc/resourcemanager_qcm6490_rb3_vision.xml /etc/
etc/resourcemanager_qcs8300_ridesx.xml /etc/
etc/resourcemanager_qcs9075_rb8.xml /etc/
etc/resourcemanager_qcs9100_ridesx.xml /etc/
etc/usecaseKvManager.xml /etc/
